services:
  app:
    image: todo-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/user/src/app
    ports:
      - 5002:3000
    container_name: todo_front
  proxy:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-front-reverse-proxy
    depends_on:
      - app
