services:
  todo-front:
    image: todo-frontend-prod
    build:
      context: todo-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    #ports:
    #- 3001:3001
    container_name: todo-frontend-prod
    depends_on:
      - todo-back
  todo-back:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    #ports:
    #- 3000:3000
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PW}@mongo:27017/the_database"
    container_name: todo-backend
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    #ports:
    #- 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: mongo-todo-app-prod
  redis:
    image: redis
    #ports:
    #- 4567:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    container_name: redis-todo-app-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - todo-front
      - todo-back
